name: Deploy static content to Pages
on:
  push:
    branches: ['main'] # 確保這是你預設的分支名稱

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build
        env:
          # 讀取 Secrets 的語法：${{ secrets.變數名稱 }}
          VITE_UNIVER_LICENSE: ${{ secrets.VITE_UNIVER_LICENSE }}
          
          # 讀取 Variables 的語法：${{ vars.變數名稱 }}
          # VITE_API_BASE_URL: ${{ vars.VITE_API_BASE_URL }}

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4